myprop.username=springboot
myprop.port=${random.int(1,100)}
spring.profiles.active=prod

spring.banner.location.classpath:banner.txt

# MariaDB 연결 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab

# JPA 설정
# update로 설정하면 Entity 클래스를 보고 자동으로 테이블을 생성/수정해 줍니다.
spring.jpa.hibernate.ddl-auto=update
# JPA가 실행하는 SQL 쿼리를 콘솔에서 볼 수 있게 해줍니다.
spring.jpa.show-sql=true