logging.level.com.rookies5=debug
# spring.test.database.replace=none

# 선택: H2 + 스키마 자동 생성을 테스트에서만 명시하고 싶을 때
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop


